// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlxLSNJbjSQABkaPcKM2UEL4z5FLRZIko',
    appId: '1:654922975976:web:18dc97e1dc8d15aad0575d',
    messagingSenderId: '654922975976',
    projectId: 'newsgram1-c2b7f',
    authDomain: 'newsgram1-c2b7f.firebaseapp.com',
    storageBucket: 'newsgram1-c2b7f.firebasestorage.app',
    measurementId: 'G-KD6TQ6E84Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmUxpsSZPiaiwspVIEYJy1vcl_7GWnFO4',
    appId: '1:654922975976:android:e6657ecaaa76b5aed0575d',
    messagingSenderId: '654922975976',
    projectId: 'newsgram1-c2b7f',
    storageBucket: 'newsgram1-c2b7f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkLIFwfiooB1R6ztNcVlhdl5IhcYIm3XQ',
    appId: '1:654922975976:ios:41b993fa44a1767ed0575d',
    messagingSenderId: '654922975976',
    projectId: 'newsgram1-c2b7f',
    storageBucket: 'newsgram1-c2b7f.firebasestorage.app',
    iosBundleId: 'com.example.newsgram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkLIFwfiooB1R6ztNcVlhdl5IhcYIm3XQ',
    appId: '1:654922975976:ios:41b993fa44a1767ed0575d',
    messagingSenderId: '654922975976',
    projectId: 'newsgram1-c2b7f',
    storageBucket: 'newsgram1-c2b7f.firebasestorage.app',
    iosBundleId: 'com.example.newsgram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlxLSNJbjSQABkaPcKM2UEL4z5FLRZIko',
    appId: '1:654922975976:web:4a2d83c4ae0b30edd0575d',
    messagingSenderId: '654922975976',
    projectId: 'newsgram1-c2b7f',
    authDomain: 'newsgram1-c2b7f.firebaseapp.com',
    storageBucket: 'newsgram1-c2b7f.firebasestorage.app',
    measurementId: 'G-B86EGT4FL0',
  );
}
